/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__the_specislalist__0_0_1 = never;
export type PromptConfig__the_specislalist__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__the_specislalist__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__the_specislalist__0_0_1;
  variables: PromptVariables__the_specislalist__0_0_1;
  content: string;
};
export type Prompt__the_specislalist = {
  name: 'The specislalist ';
  slug: 'the-specislalist';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__the_specislalist__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    'the-specislalist': Prompt__the_specislalist;
  };
  globals: Globals;
};
