// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-analyses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.117.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable key is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-analyses.ts
import { z } from "npm:zod@^3.25.76";
var list_analyses_default = defineTool({
  name: "list_style_analyses",
  title: "List my style analyses",
  description: "Lists the signed-in user's style analyses (id, occasion, gender, image URLs, created_at), newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("style_analyses").select("id, occasion, gender, image_url, generated_image_url, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-analysis.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_analysis_default = defineTool2({
  name: "get_style_analysis",
  title: "Get a style analysis",
  description: "Fetches a single style analysis owned by the signed-in user, including the full analysis_result JSON.",
  inputSchema: {
    id: z2.string().uuid().describe("The style_analyses.id UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("style_analyses").select("*").eq("id", id).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Analysis not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { analysis: data }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_favorites_default = defineTool3({
  name: "list_favorites",
  title: "List favorites",
  description: "Lists the signed-in user's favorited style analyses with their full data.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("favorites").select("id, created_at, style_analyses(*)").order("created_at", { ascending: false }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/toggle-favorite.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var toggle_favorite_default = defineTool4({
  name: "toggle_favorite",
  title: "Add or remove a favorite",
  description: "Adds the given style analysis to the signed-in user's favorites (action=add) or removes it (action=remove).",
  inputSchema: {
    analysis_id: z4.string().uuid().describe("The style_analyses.id to favorite/unfavorite."),
    action: z4.enum(["add", "remove"]).describe("Whether to add or remove the favorite.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ analysis_id, action }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    if (action === "add") {
      const { data, error: error2 } = await supabase.from("favorites").upsert(
        { user_id: ctx.getUserId(), analysis_id },
        { onConflict: "user_id,analysis_id", ignoreDuplicates: false }
      ).select();
      if (error2)
        return { content: [{ type: "text", text: error2.message }], isError: true };
      return {
        content: [{ type: "text", text: `Added favorite for analysis ${analysis_id}` }],
        structuredContent: { favorite: data?.[0] ?? null }
      };
    }
    const { error } = await supabase.from("favorites").delete().eq("user_id", ctx.getUserId()).eq("analysis_id", analysis_id);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Removed favorite for analysis ${analysis_id}` }]
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vmgxojtcriaapvzyyrcl";
var mcp_default = defineMcp({
  name: "style-ai-assistant",
  title: "Style AI Assistant",
  version: "0.1.0",
  instructions: "Tools for The Special Style. Use list_style_analyses / get_style_analysis to read the signed-in user's outfit analyses, and list_favorites / toggle_favorite to manage their favorites.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_analyses_default, get_analysis_default, list_favorites_default, toggle_favorite_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
